refactor and demo logging; demo colors

diff --git a/cli0 b/cli0
--- a/cli0
+++ b/cli0
@@ -2,29 +2,23 @@
 
 ##### utilities
 
-function out() { printf "%s\n" "$*" >&1; } # stdout for output to be consumed by programs
-function msg() { printf "%b\n" "$*" >&2; } # stderr for messaging to be read by users; may use color if [ -t 2 ] is true
+function out() { printf "%s\n" "$*" >&1; } # stdout for output to be consumed by programs; adds a newline add end
+function msg() { printf "%b" "$*" >&2; } # stderr for messaging to be read by users; may use color if [ -t 2 ] is true; BYONL (newlines not supplied here)
 
-function info() {
+function log() {
+  local -r hue="$1" # [0,1];[30-37]m ..e.g. 0;32m for plain green, 1;31m for bold red
+  local -r label="$2" # when not printing color (to terminal), label will be added for differentiation
+  shift; shift
   local -r pre="$(basename "$0"):"
-  local -r col_='\033[1;32m' # light green
-  local -r _col='\033[0m'
-  if [ -t 2 ]; then msg "$col_$pre $*$_col" && return 0; else msg "$pre --- $*" && return 0; fi
+  local -r col_='\033['; local -r _col='\033[0m'
+  if [ -t 2 ]; then msg "$col_$hue$pre $*$_col\n" && return 0; else msg "$pre $label $*\n" && return 0; fi
 }
 
-function warn() {
-  local -r pre="$(basename "$0"):"
-  local -r col_='\033[1;33m' # light orange
-  local -r _col='\033[0m'
-  if [ -t 2 ]; then msg "$col_$pre $*$_col" && return 0; else msg "$pre warn $*" && return 0; fi
-}
-
-function error() {
-  local -r pre="$(basename "$0"):"
-  local -r col_='\033[1;31m' # light red
-  local -r _col='\033[0m'
-  if [ -t 2 ]; then msg "$col_$pre $*$_col" && return 0; else msg "$pre error $*" && return 0; fi
-}
+function debug() { log '0;37m' '::' "$*" ; } # plain/dark white
+function note()  { log '0;36m' '--' "$*" ; } # plain/dark cyan
+function info()  { log '0;32m' '---' "$*" ; } # plain/dark green
+function warn()  { log '0;33m' 'warn' "$*" ; } # plain/dark orange
+function error() { log '1;31m' 'error' "$*" ; } # bold/light red
 
 function exit_on_error() {
   local -r exit_code=$1
@@ -49,7 +43,7 @@ usage:
 
 options:
   -h --help   show this usage info
-  <service>   foo, bar, baz
+  <service>   see, say, foo, bar, baz
 
 EOM
 }
@@ -64,8 +58,35 @@ function do_thing() {
   local -r svc="$1"
   local -r rn=$(rando 0 100)
 
-  msg "$svc $rn"
+  msg "$svc $rn\n"
   if [[ "$rn" -gt 49 ]]; then return 1; else return 0; fi
+}
+
+function say_things() {
+  local -r rn=$(rando 0 100)
+
+  debug "this is a debug message"
+  note "this is a note message"
+  info "this is a info message"
+  warn "this is a warn message"
+  error "this is an error message"
+
+  return 0
+}
+
+function see_things() {
+  # credit: Daniel Crisman, from https://tldp.org/HOWTO/Bash-Prompt-HOWTO/x329.html
+  local -r T='gYw' # The test text
+
+  msg "                 40m     41m     42m     43m     44m     45m     46m     47m\n";
+  for FGs in '    m' '   1m' '  30m' '1;30m' '  31m' '1;31m' '  32m' '1;32m' '  33m' '1;33m' '  34m' '1;34m' '  35m' '1;35m' '  36m' '1;36m' '  37m' '1;37m';
+    do FG=${FGs// /}
+    msg " $FGs \033[$FG  $T  "
+    for BG in 40m 41m 42m 43m 44m 45m 46m 47m;
+      do msg "$EINS \033[$FG\033[$BG  $T  \033[0m";
+    done
+    msg "\n"
+  done
 }
 
 
@@ -81,15 +102,15 @@ do
       usage 1 && exit 0 # program asked to generate output, so explicitly send to stdout ( &1 )
       ;;
 
-    foo|bar|baz)
+    foo|bar|baz|say|see)
       SERVICE="$opt"
       shift # past value
       ;;
 
-    *)    # unmatched option
-      echo ""
+    *)      # unmatched option
+      msg "\n"
       warn "error: unknown option '$opt'."
-      echo ""
+      msg "\n"
       exit 1
       ;;
   esac
@@ -97,30 +118,43 @@ done
 
 case $SERVICE in
   foo)
-    info "preparing to foo.."
+    note "preparing to foo.."
     do_thing "foo"
     ;;
 
   bar)
-    info "starting to bar.."
+    note "starting to bar.."
     do_thing "bar"
     ;;
 
   baz)
-    info "beginning to baz.."
+    note "beginning to baz.."
     do_thing "baz"
     ;;
 
+  see)
+    note "printing basic palette.."
+    msg "\n"
+    see_things
+    ;;
+
+  say)
+    note "preparing to speak.."
+    msg "\n"
+    say_things
+    ;;
+
   *)    # unmatched option
-    warn ""
+    msg "\n"
     warn "error: unknown service '$SERVICE'"
-    warn ""
+    msg "\n"
     exit 1
     ;;
 esac
 
 exit_on_error $? "$SERVICE failed\n"
 
+msg "\n"
 info "done."
-echo ""
+msg "\n"
 exit 0
